version: '3'

volumes:
  database_data:
    driver: local

services:
  webtest: # 容器名字
    #     image: liudongkenny/rpc:v3
    build: .
    command: go run main.go
    environment:
      - APP_ENV=debug
      - DOMAIN=localhost
      - TZ=Asia/Shanghai
    volumes:
      - .:/go/src/dev-framework-go/
    ports:
      - "8890:8890" # 将内部的 8890 映射到外部的 6000
    depends_on:
      - db
      - redis

  webrelease: # 容器名字
#     image: liudongkenny/rpc:v3
    build: .
    command: go run main.go
    environment:
      - APP_ENV=release
      - DOMAIN=47.93.19.60
      - TZ=Asia/Shanghai
    volumes:
      - .:/go/src/dev-framework-go/
    ports:
      - "8890:8890" # 将内部的 8890 映射到外部的 6000
    depends_on:
      - db
      - redis
  db:
    image: postgres:9.4
    volumes:
      - database_data:/var/lib/postgresql/data/
    ports:
      - "3432:5432"
    restart: always

  redis:
    image: redis:rc-alpine3.11
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    restart: always
