info:
  contact: {}
  license: {}
paths:
  /api/v1/login:
    get:
      consumes:
      - application/json
      description: 通过用户的账号和密码登录
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'code": 100, "msg": "success", "data":nil}'
          schema:
            type: string
      summary: 用户登录
swagger: "2.0"
