host: localhost:8890
info:
  contact:
    email: 846723063@qq.com
    name: kennyL
  description: 开发接口文档
  license: {}
  termsOfService: http://swagger.io/terms/
  title: gin脚手脚
  version: "1.0"
paths:
  /api/v1/login:
    get:
      consumes:
      - application/json
      description: 通过用户的账号和密码登录
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'code": 100, "msg": "success", "data":nil}'
          schema:
            type: string
      summary: 用户登录
swagger: "2.0"
